### ISSUE TITLE
heap-buffer-overflow

### ISSUE THREAD

**Issue by Krystalz42** [Krystalz42/nibbler#15]
1SCER
2CERD

Random pop    

 #0 0x102afaa89 in WidgetChat::colorLog::colorLog(WidgetChat::colorLog&&) WidgetChat.hpp:9
    #1 0x102afa9bc in WidgetChat::colorLog::colorLog(WidgetChat::colorLog&&) WidgetChat.hpp:9
    #2 0x102afb8bc in std::__1::vector<WidgetChat::colorLog, std::__1::allocator<WidgetChat::colorLog> >::__swap_out_circular_buffer(std::__1::__split_buffer<WidgetChat::colorLog, std::__1::allocator<WidgetChat::colorLog>&>&) memory:1805
    #3 0x102afa18b in void std::__1::vector<WidgetChat::colorLog, std::__1::allocator<WidgetChat::colorLog> >::__push_back_slow_path<WidgetChat::colorLog>(WidgetChat::colorLog&&) vector:1582
    #4 0x102af50d6 in WidgetChat::addLog(eColorLog, char const*, ...) vector:1619
    #5 0x102b27fd1 in void Gui::addMessageChat<>(eColorLog, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) Gui.hpp:40
    #6 0x102ccf693 in SnakeClient::callbackDeadConnection() SnakeClient.cpp:281

**Comment by Krystalz42** [comment]
J'ai proteger la gui, c'est bizarre :/
