### ISSUE TITLE
 heap-buffer-overflow 

### ISSUE THREAD

**Issue by Krystalz42** [Krystalz42/nibbler#16]
==26671==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c0000bd300 at pc 0x00010106d436 bp 0x7ffeeec4ea10 sp 0x7ffeeec4ea08
READ of size 4 at 0x60c0000bd300 thread T0
    #0 0x10106d435 in WidgetChat::beginContent_() WidgetChat.cpp:13
    #1 0x10106945e in AWidget::render(bool) AWidget.cpp:41
    #2 0x1010b6a15 in Gui::aState() Gui.cpp:176
    #3 0x100fb77ce in nibbler(Univers&) main.cpp:14
    #4 0x100fbc5f7 in main main.cpp:106
    #5 0x7fff79500ed8 in start (libdyld.dylib:x86_64+0x16ed8)

**Comment by Krystalz42** [comment]
1SCERD
